# Generated by Django 4.1.6 on 2023-02-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_customuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('Qoraqalpogʻiston', 'Qoraqalpogʻiston'), ('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Jizzax', 'Jizzax'), ('Qashqadaryo', 'Qashqadaryo'), ('Navoiy', 'Navoiy'), ('Namangan', 'Namangan'), ('Samarqand', 'Samarqand'), ('Surxondaryo', 'Surxondaryo'), ('Sirdaryo', 'Sirdaryo'), ('Toshkent shahri', 'Toshkent shahri'), ('Toshkent viloyati', 'Toshkent viloyati'), ('Fargʻona', 'Fargʻona'), ('Xorazm', 'Xorazm')], default='Toshkent shahri', max_length=30),
        ),
    ]
