# Generated by Django 4.1.6 on 2023-02-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_customuser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='/static/images/default_profile_pic.jpg', upload_to='profile_images/'),
        ),
    ]
