# Generated by Django 4.1.6 on 2023-02-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_alter_customuser_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(choices=[('Karakalpakistan', 'Karakalpakistan'), ('Andijan', 'Andijan'), ('Bukhara', 'Bukhara'), ('Djizzak', 'Djizzak'), ('Kashkadarya', 'Kashkadarya'), ('Navoi', 'Navoi'), ('Namangan', 'Namangan'), ('Samarkand', 'Samarkand'), ('Surkhandarya', 'Surkhandarya'), ('Syrdarya', 'Syrdarya'), ('Tashkent', 'Tashkent'), ('Tashkent province', 'Tashkent province'), ('Fergana', 'Fergana'), ('Khorezm', 'Khorezm')], default='Tashkent', max_length=30),
        ),
    ]
