# Generated by Django 4.1.6 on 2023-02-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('exist', 'exist'), ('using', 'using'), ('need', 'need')], max_length=10),
        ),
    ]
