# Generated by Django 4.1.6 on 2023-02-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books_app', '0003_alter_book_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('end', 'end')], default='ongoing', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_exchanges_1', to='books_app.book')),
                ('book2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_exchanges_2', to='books_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='EndExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_exchange_requests', to='book_exchange_app.bookexchange')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_exchange_requests_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_exchange_requests_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('for_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_book', to='books_app.book')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_requests_from_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
