# Generated by Django 4.1.6 on 2023-02-10 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrequest',
            options={'ordering': ['-created_at']},
        ),
    ]
