# Generated by Django 4.1.6 on 2023-02-10 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_exchange_app', '0002_alter_bookrequest_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookexchange',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='endexchangerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='endexchangerequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
